# Generated by Django 4.2.7 on 2026-01-02 21:17

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('product_interest', models.CharField(choices=[('greenhouse_ai', 'TerraLink Greenhouse AI'), ('drone_validator', 'TerraLink Drone Validator'), ('both', 'Both'), ('general', 'General Inquiry')], default='general', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='contact_uploads/')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('honeypot', models.CharField(blank=True, max_length=50, validators=[contact.models.validate_honeypot])),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contact_con_created_4915e5_idx'), models.Index(fields=['status'], name='contact_con_status_d76e5c_idx')],
            },
        ),
    ]
