# Generated by Django 4.2.7 on 2026-01-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('country', models.CharField(default='Kazakhstan', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration_months', models.IntegerField(default=6, help_text='Expected duration in months')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('progress_percent', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('description', models.TextField(blank=True)),
                ('nda_notice', models.TextField(blank=True, default='Pilot location details are subject to NDA. Contact us for more information.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
