# Generated by Django 4.2.7 on 2026-01-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ai', 'AI Subscription'), ('drone', 'Drone Service')], max_length=20)),
                ('price_range_text', models.CharField(help_text="e.g., '450,000 - 3,500,000 KZT / month'", max_length=200)),
                ('monthly_kzt_min', models.IntegerField(help_text='Minimum price in KZT')),
                ('monthly_kzt_max', models.IntegerField(help_text='Maximum price in KZT')),
                ('details', models.TextField(help_text="Pricing details and what's included")),
                ('is_pilot_eligible', models.BooleanField(default=False, help_text='Is this eligible for pilot pricing?')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'order', 'monthly_kzt_min'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(max_length=300)),
                ('long_description', models.TextField()),
                ('type', models.CharField(choices=[('ai', 'TerraLink Greenhouse AI'), ('drone', 'TerraLink Drone Validator')], max_length=20)),
                ('status', models.CharField(choices=[('concept', 'Concept'), ('mvp', 'MVP'), ('pilot', 'Pilot'), ('production', 'Production')], max_length=20)),
                ('features', models.JSONField(default=list, help_text='List of feature strings')),
                ('icon_svg', models.TextField(blank=True, help_text='SVG icon code')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
